(() => {
  const SCHEMA_VERSION = 2;
  const CONFIG_ENDPOINT = '';
  const SUBMISSION_ENDPOINT = '';
  const params = new URLSearchParams(location.search);
  const linkToken = params.get('access') || '';
  const STORAGE_KEY = linkToken ? `waimarinoSpeedShearEntryManagerV2_${linkToken}` : 'waimarinoSpeedShearEntryManagerV2_manual';
  const $ = id => document.getElementById(id);
  const els = {
    competitionName:$('competitionName'),competitionDate:$('competitionDate'),venue:$('venue'),bookingReference:$('bookingReference'),setupNotice:$('setupNotice'),
    publicEntryCard:$('publicEntryCard'),publicEntryUrl:$('publicEntryUrl'),copyPublicEntryBtn:$('copyPublicEntryBtn'),refreshEntriesBtn:$('refreshEntriesBtn'),publicEntryStatus:$('publicEntryStatus'),
    openPublicEntriesBtn:$('openPublicEntriesBtn'),closePublicEntriesBtn:$('closePublicEntriesBtn'),autoCloseAt:$('autoCloseAt'),defaultCutoffNote:$('defaultCutoffNote'),saveEntryControlsBtn:$('saveEntryControlsBtn'),clearScheduleBtn:$('clearScheduleBtn'),entryControlsStatus:$('entryControlsStatus'),
    gradeSelect:$('gradeSelect'),customGrade:$('customGrade'),addGradeBtn:$('addGradeBtn'),gradesContainer:$('gradesContainer'),submitAllBtn:$('submitAllBtn'),downloadAllBtn:$('downloadAllBtn'),loadBtn:$('loadBtn'),loadFile:$('loadFile'),globalStatus:$('globalStatus'),
    dialog:$('confirmDialog'),dialogTitle:$('dialogTitle'),dialogBody:$('dialogBody'),dialogActions:$('dialogActions'),savedToast:$('savedToast')
  };

  let state={schemaVersion:SCHEMA_VERSION,type:'speed_shear_entry_manager',bookingReference:'',accessToken:linkToken,publicEntryUrl:'',competition:{name:'',date:'',venue:''},entrySettings:{publicEntriesOpen:true,autoCloseAt:''},grades:[],submissionHistory:[]};
  let saveTimer;

  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function clean(v){return String(v||'').trim().replace(/\s+/g,' ');}
  function key(v){return clean(v).toLowerCase();}
  function uid(){return crypto.randomUUID?.()||`id-${Date.now()}-${Math.random().toString(16).slice(2)}`;}
  function capitalizeWordSegment(value){const lower=String(value||'').toLowerCase(),idx=lower.search(/[a-z]/i);return idx<0?lower:lower.slice(0,idx)+lower.charAt(idx).toUpperCase()+lower.slice(idx+1);}
  const ACRONYM_WHITELIST={NZ:'NZ',US:'US',USA:'USA',UK:'UK',UAE:'UAE',EU:'EU',SA:'SA',AU:'AU',AUS:'AUS',NSW:'NSW',VIC:'VIC',QLD:'QLD',ACT:'ACT',WA:'WA',NT:'NT','A&P':'A&P'};
  function smartTitle(value){const text=clean(value);if(!text)return '';return text.split(' ').map(word=>word.split('-').map(part=>{const m=part.match(/(^[^A-Za-z0-9]*)([A-Za-z0-9&']+)([^A-Za-z0-9]*$)/);if(!m)return capitalizeWordSegment(part);const [,lead,core,trail]=m,upper=core.toUpperCase();let r='';if(upper==='MT')r='Mt';else if(Object.prototype.hasOwnProperty.call(ACRONYM_WHITELIST,upper))r=ACRONYM_WHITELIST[upper];else if(/^[A-Z]{2,4}$/.test(core))r=core;else{r=core.split("'").map(capitalizeWordSegment).join("'");r=r.replace(/^Mc([a-z])/,(_m,c)=>`Mc${c.toUpperCase()}`);}return `${lead}${r}${trail}`;}).join('-')).join(' ');}
  function competitorKey(c){return `${key(c.name)}|${key(c.town)}`;}
  function gradeById(id){return state.grades.find(g=>g.id===id);}
  function gradeByName(name){return state.grades.find(g=>key(g.name)===key(name));}
  function newGrade(name,meta={}){return {id:meta.id||uid(),name:clean(name),competitors:[],submissionVersion:Number(meta.submissionVersion||0),lastSubmittedAt:meta.lastSubmittedAt||null,publicOpen:meta.publicOpen!==false,entryLimit:Number(meta.entryLimit)>0?Number(meta.entryLimit):null,submitted:meta.submitted===true,submittedAt:meta.submittedAt||null};}
  function setStatus(msg,kind=''){els.globalStatus.className=`status ${kind}`;els.globalStatus.textContent=msg||'';}
  function syncHeaderToState(){state.competition.name=clean(els.competitionName.value);state.competition.date=els.competitionDate.value||'';state.competition.venue=clean(els.venue.value);state.bookingReference=clean(els.bookingReference.value);}
  function persist(){syncHeaderToState();localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
  function scheduleSave(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>{persist();els.savedToast.classList.add('show');setTimeout(()=>els.savedToast.classList.remove('show'),900);},400);}
  function isoToLocalInput(value){if(!value)return '';const d=new Date(value);if(Number.isNaN(d.getTime()))return '';const local=new Date(d.getTime()-d.getTimezoneOffset()*60000);return local.toISOString().slice(0,16);}
  function localInputToIso(value){if(!value)return '';const d=new Date(value);return Number.isNaN(d.getTime())?'':d.toISOString();}
  function defaultFinalCutoff(){if(!state.competition.date)return '';const d=new Date(`${state.competition.date}T00:00:00`);if(Number.isNaN(d.getTime()))return '';d.setDate(d.getDate()+1);d.setHours(12,0,0,0);return d.toISOString();}
  function publicEntriesEffectivelyOpen(){if(state.entrySettings.publicEntriesOpen===false)return false;const raw=state.entrySettings.autoCloseAt||defaultFinalCutoff();if(!raw)return true;const d=new Date(raw);return Number.isNaN(d.getTime())||Date.now()<d.getTime();}
  function gradeCount(g){return g.competitors.length;}
  function gradeFull(g){return Boolean(g.entryLimit&&gradeCount(g)>=g.entryLimit);}
  function gradePublicOpen(g){return publicEntriesEffectivelyOpen()&&g.publicOpen!==false&&!g.submitted&&!gradeFull(g);}
  function allGradesSubmitted(){return state.grades.length>0&&state.grades.every(g=>g.submitted===true);}
  function gradeStatus(g){if(g.submitted)return 'Submitted';if(gradeFull(g))return 'Full';if(!g.publicOpen)return 'Public Closed';if(!publicEntriesEffectivelyOpen())return 'Public Closed';return 'Public Open';}

  function dialogChoice(title,html,choices){return new Promise(resolve=>{els.dialogTitle.textContent=title;els.dialogBody.innerHTML=html;els.dialogActions.innerHTML='';choices.forEach(choice=>{const b=document.createElement('button');b.type='button';b.textContent=choice.label;b.className=choice.primary?'primary':'secondary';b.addEventListener('click',()=>{els.dialog.close();resolve(choice.value);},{once:true});els.dialogActions.appendChild(b);});els.dialog.showModal();const onCancel=()=>resolve(null);els.dialog.addEventListener('cancel',onCancel,{once:true});});}

  function renderHeader(){els.competitionName.value=state.competition.name||'';els.competitionDate.value=state.competition.date||'';els.venue.value=state.competition.venue||'';els.bookingReference.value=state.bookingReference||'';if(state.publicEntryUrl){els.publicEntryUrl.value=state.publicEntryUrl;els.publicEntryCard.classList.remove('hidden');}els.autoCloseAt.value=isoToLocalInput(state.entrySettings.autoCloseAt||'');const finalCutoff=defaultFinalCutoff();els.defaultCutoffNote.textContent=state.entrySettings.autoCloseAt?'A custom closing time is set. The final automatic shutdown fallback is not used while this is set.':(finalCutoff?'No custom cutoff set. Final automatic shutdown is 12 hours after the competition day ends.':'If left blank, the public form automatically shuts down 12 hours after the competition day ends.');const open=publicEntriesEffectivelyOpen();els.publicEntryStatus.textContent=`Public entries: ${open?'Open':'Closed'}`;els.publicEntryStatus.className=`badge ${open?'green':'closed'}`;els.openPublicEntriesBtn.disabled=open&&state.entrySettings.publicEntriesOpen!==false;els.closePublicEntriesBtn.disabled=state.entrySettings.publicEntriesOpen===false;}
  function checkedCount(g){return g.competitors.filter(c=>c.checkedIn).length;}
  function publicCount(g){return g.competitors.filter(c=>c.source==='public-entry').length;}
  function render(){
    renderHeader();
    if(!state.grades.length){els.gradesContainer.innerHTML='<p class="status">No grades or events added yet.</p>';return;}
    els.gradesContainer.innerHTML=state.grades.map(g=>{
      const count=gradeCount(g),status=gradeStatus(g),remaining=g.entryLimit?Math.max(0,g.entryLimit-count):null;
      const rows=g.competitors.map((c,i)=>`<tr data-cid="${esc(c.id)}"><td>${i+1}</td><td><input data-edit="name" value="${esc(c.name)}"></td><td><input data-edit="town" value="${esc(c.town)}"></td><td><div>${esc(c.phone||'')}</div><div class="small-note">${esc(c.email||'')}</div></td><td><button class="check-btn ${c.checkedIn?'checked':''}" data-action="toggle-check">${c.checkedIn?'Checked In ✓':'Not Checked In'}</button></td><td><button class="secondary" data-action="remove-competitor">Remove</button></td></tr>`).join('');
      const statusClass=g.submitted?'submitted':gradeFull(g)?'full':gradePublicOpen(g)?'green':'closed';
      const limitText=g.entryLimit?`${count}/${g.entryLimit}${remaining?` — ${remaining} place${remaining===1?'':'s'} left`:''}`:`${count} entered — no limit`;
      return `<article class="grade-card ${g.submitted?'submitted':gradeFull(g)?'full':''}" data-grade-id="${esc(g.id)}">
        <div class="grade-head"><div><h3>${esc(g.name)}</h3><div class="badges"><span class="badge">Total: ${count}</span><span class="badge green">Checked in: ${checkedCount(g)}</span>${publicCount(g)?`<span class="badge public">Online: ${publicCount(g)}</span>`:''}<span class="badge ${statusClass}">${esc(status)}</span><span class="badge ${gradeFull(g)?'full':''}">${esc(limitText)}</span></div></div>
        <div class="grade-actions"><button data-action="submit-grade">${g.submitted?'Resubmit':'Submit'} ${esc(g.name)} Entries</button><button class="secondary" data-action="download-grade">Download</button><button class="secondary" data-action="remove-grade">Remove Grade</button></div></div>
        <div class="grade-public-controls"><div><label>Public entries for ${esc(g.name)}</label><div class="entry-control-actions"><button data-action="open-grade-public" ${g.submitted?'disabled':''}>Open</button><button class="secondary" data-action="close-grade-public">Close</button></div><p class="small-note">Submitting this grade automatically closes it to public entries. Manual staff entry stays available.</p></div>
        <div><label>Optional entry limit</label><div class="limit-row"><input data-role="entry-limit" type="number" min="1" step="1" value="${g.entryLimit||''}" placeholder="No limit"><button class="secondary" data-action="save-limit">Save</button></div><p class="small-note">Manual and public entries both count toward this total.</p></div></div>
        <div class="quick-row"><input data-role="quick-name" placeholder="Competitor name"><input data-role="quick-town" placeholder="Hometown (optional)"><button data-action="add-competitor">Add Competitor</button></div>
        <div class="bulk"><details><summary><strong>Add a list of names</strong></summary><textarea data-role="bulk-text" placeholder="One competitor per line. Name or Name, Town"></textarea><div class="bulk-actions"><button data-action="bulk-add">Add From List</button><span class="status" data-role="bulk-status"></span></div></details></div>
        <table class="competitor-table"><thead><tr><th>#</th><th>Name</th><th>Town</th><th>Contact</th><th>Check-in</th><th>Remove</th></tr></thead><tbody>${rows||'<tr><td colspan="6">No competitors added yet.</td></tr>'}</tbody></table>
      </article>`;
    }).join('');
  }

  async function postManager(payload){if(!SUBMISSION_ENDPOINT)return {ok:false,offline:true};try{await fetch(SUBMISSION_ENDPOINT,{method:'POST',mode:'no-cors',cache:'no-store',headers:{'Content-Type':'text/plain;charset=UTF-8'},body:JSON.stringify(payload)});return {ok:true};}catch(error){return {ok:false,error};}}
  async function saveCompetitorCentral(g,c){return postManager({type:'speed_shear_manager_competitor_upsert',accessToken:state.accessToken,competitor:{id:c.id,grade:g.name,name:c.name,town:c.town,phone:c.phone||'',email:c.email||'',source:c.source||'manual',checkedIn:c.checkedIn===true,createdAt:c.createdAt||''}});}
  function addCompetitorLocal(gradeId,name,town='',extra={}){const g=gradeById(gradeId);if(!g)return null;const c={id:extra.id||uid(),name:smartTitle(name),town:smartTitle(town),phone:clean(extra.phone),email:clean(extra.email),source:extra.source||'manual',checkedIn:Boolean(extra.checkedIn),createdAt:extra.createdAt||new Date().toISOString()};if(!c.name||g.competitors.some(x=>competitorKey(x)===competitorKey(c)))return null;g.competitors.push(c);return c;}
  function parseLine(line){const text=clean(line);if(!text)return null;const comma=text.indexOf(',');if(comma>=0)return{name:clean(text.slice(0,comma)),town:clean(text.slice(comma+1))};const tab=text.match(/^(.*?)\t+(.*)$/);if(tab)return{name:clean(tab[1]),town:clean(tab[2])};const dash=text.match(/^(.*?)\s+[\-–—]\s+(.*)$/);if(dash)return{name:clean(dash[1]),town:clean(dash[2])};const spaces=text.match(/^(.*?)\s{2,}(\S.*)$/);if(spaces)return{name:clean(spaces[1]),town:clean(spaces[2])};return{name:text,town:''};}

  async function addGrade(name){name=clean(name);if(!name)return;if(gradeByName(name))return setStatus(`${name} already exists.`,'warn');if(SUBMISSION_ENDPOINT){const r=await postManager({type:'speed_shear_manager_grade_add',accessToken:state.accessToken,grade:name});if(!r.ok)return setStatus('Could not add that grade to the shared competition.','warn');}state.grades.push(newGrade(name));els.customGrade.value='';render();scheduleSave();}
  async function saveGlobalSettings(settings){state.entrySettings={...state.entrySettings,...settings};render();persist();if(SUBMISSION_ENDPOINT){const r=await postManager({type:'speed_shear_manager_entry_settings',accessToken:state.accessToken,entrySettings:{...state.entrySettings}});if(!r.ok)return false;await fetchCompetitionSetup(false);}return true;}
  async function saveGradeSettings(g){if(SUBMISSION_ENDPOINT){const r=await postManager({type:'speed_shear_manager_grade_settings',accessToken:state.accessToken,grade:g.name,gradeSettings:{publicOpen:g.publicOpen!==false,entryLimit:g.entryLimit}});if(!r.ok)return false;}scheduleSave();return true;}

  function submissionPayload(grades,mode){syncHeaderToState();return{schemaVersion:2,type:'speed_shear_roster_submission',bookingReference:state.bookingReference,accessToken:state.accessToken,competition:{...state.competition},submission:{mode,submittedAt:new Date().toISOString()},grades:Object.fromEntries(grades.map(g=>[g.name,g.competitors.filter(c=>c.checkedIn).map(c=>({name:c.name,town:c.town||''}))]))};}
  function unconfirmed(grades){return grades.flatMap(g=>g.competitors.filter(c=>!c.checkedIn).map(c=>({grade:g.name,name:c.name}));}
  async function confirmSubmission(grades,label){const missing=unconfirmed(grades),included=grades.reduce((n,g)=>n+checkedCount(g),0);if(!included){setStatus('There are no checked-in competitors to submit.','warn');return false;}if(!missing.length)return true;const choice=await dialogChoice(`Submit ${label}?`,`<p><strong>${included} checked-in competitor${included===1?'':'s'} will be submitted.</strong></p><p>${missing.length} competitor${missing.length===1?' has':'s have'} not been checked in and will not be included:</p><ul>${missing.map(x=>`<li><strong>${esc(x.name)}</strong>${grades.length>1?` — ${esc(x.grade)}`:''}</li>`).join('')}</ul>`,[{label:'Go Back',value:'cancel'},{label:'Submit Checked-In Entries',value:'submit',primary:true}]);return choice==='submit';}
  function filename(payload,suffix){const comp=(payload.competition.name||'Competition').replace(/[^a-z0-9]+/gi,'_').replace(/^_|_$/g,'');return`${comp}_${payload.bookingReference||'NoRef'}_${suffix}.json`;}
  function downloadJson(payload,name){const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}
  async function promptAllSubmitted(){const choice=await dialogChoice('All grades and events submitted','<p><strong>All grade and event rosters have now been submitted.</strong></p><p>There are no remaining grades available for public entry. Would you like to close the public competitor entry link now?</p>',[{label:'Keep Link Open',value:'keep'},{label:'Close Public Entries',value:'close',primary:true}]);if(choice==='close'){await saveGlobalSettings({publicEntriesOpen:false});setStatus('All rosters submitted. Public entries closed.','ok');}}
  async function sendSubmission(grades,mode,label){if(!await confirmSubmission(grades,label))return;const payload=submissionPayload(grades,mode);if(SUBMISSION_ENDPOINT){const r=await postManager(payload);if(!r.ok){downloadJson(payload,filename(payload,mode==='all'?'AllEntries':label));return setStatus('Could not send submission. Backup roster downloaded.','warn');}setStatus(`${label} submission sent.`,'ok');}else{downloadJson(payload,filename(payload,mode==='all'?'AllEntries':label));setStatus('Backend is not deployed yet. Submission file downloaded for testing.','warn');}
    const now=new Date().toISOString();grades.forEach(g=>{g.submissionVersion=(g.submissionVersion||0)+1;g.lastSubmittedAt=now;g.submitted=true;g.submittedAt=now;g.publicOpen=false;});state.submissionHistory.push({mode,grades:grades.map(g=>g.name),submittedAt:now});render();scheduleSave();if(allGradesSubmitted())await promptAllSubmitted();}

  async function fetchCompetitionSetup(showMessage=false){const token=state.accessToken||linkToken;if(!token)return;if(!CONFIG_ENDPOINT){els.setupNotice.textContent='This competition link is ready for backend connection. The live booking handoff has not been deployed yet.';els.setupNotice.classList.remove('hidden');return;}try{const r=await fetch(`${CONFIG_ENDPOINT}?action=entry-manager&access=${encodeURIComponent(token)}`,{cache:'no-store'}),setup=await r.json();if(!setup.ok)throw new Error(setup.error||'Could not load competition');applySetup(setup);if(showMessage)setStatus('Shared competition state refreshed.','ok');}catch(_){setStatus('Could not refresh this competition.','warn');}}
  function applySetup(setup){state.bookingReference=setup.bookingReference||state.bookingReference;state.accessToken=setup.accessToken||state.accessToken||linkToken;state.publicEntryUrl=setup.competitorEntryUrl||state.publicEntryUrl;state.competition={...state.competition,...(setup.competition||{})};state.entrySettings={publicEntriesOpen:setup.entrySettings?.publicEntriesOpen!==false,autoCloseAt:setup.entrySettings?.autoCloseAt||''};const old=new Map(state.grades.map(g=>[key(g.name),g]));const names=Array.isArray(setup.grades)?setup.grades:Object.keys(setup.competitionSetup?.events||{});state.grades=names.map(name=>{const previous=old.get(key(name))||{},remote=setup.gradeSettings?.[name]||{};return newGrade(name,{...previous,...remote,entryLimit:remote.entryLimit??previous.entryLimit,publicOpen:remote.publicOpen??previous.publicOpen,submitted:remote.submitted??previous.submitted,submittedAt:remote.submittedAt??previous.submittedAt});});(setup.competitors||[]).forEach(entry=>{let g=gradeByName(entry.grade);if(!g){g=newGrade(entry.grade);state.grades.push(g);}addCompetitorLocal(g.id,entry.name,entry.town,{...entry,checkedIn:entry.checkedIn===true,source:entry.source||'manual'});});els.setupNotice.textContent='Competition details, entries, grade status and check-in state are loaded from the shared competition record.';els.setupNotice.classList.remove('hidden');render();persist();}

  async function closePublicEntries(){const choice=await dialogChoice('Close public entries','<p>How do you want to close the public competitor entry link?</p><p>Your scheduled/custom closing time can remain in place if this is only a temporary closure.</p>',[{label:'Cancel — Leave Open',value:'cancel'},{label:'Close Temporarily — Keep Scheduled Cutoff',value:'temporary'},{label:'Close and Cancel Custom Cutoff',value:'permanent',primary:true}]);if(choice==='temporary'){if(await saveGlobalSettings({publicEntriesOpen:false}))setStatus('Public entries temporarily closed. Scheduled cutoff kept.','ok');}if(choice==='permanent'){if(await saveGlobalSettings({publicEntriesOpen:false,autoCloseAt:''}))setStatus('Public entries closed. Custom cutoff removed; final post-event shutdown remains as the fallback.','ok');}}
  async function openPublicEntries(){const cutoff=state.entrySettings.autoCloseAt;const choice=await dialogChoice('Open public entries',cutoff?`<p>Public entries will reopen. Your scheduled closing time of <strong>${esc(new Date(cutoff).toLocaleString('en-NZ'))}</strong> will remain in place.</p>`:'<p>Public entries will reopen. No custom cutoff is set, so the default final shutdown after the competition will remain in place.</p>',[{label:'Cancel',value:'cancel'},{label:'Open Public Entries',value:'open',primary:true}]);if(choice==='open'&&await saveGlobalSettings({publicEntriesOpen:true}))setStatus('Public entries reopened.','ok');}

  els.gradeSelect.addEventListener('change',()=>els.customGrade.classList.toggle('hidden',els.gradeSelect.value!=='__custom__'));
  els.addGradeBtn.addEventListener('click',()=>addGrade(els.gradeSelect.value==='__custom__'?els.customGrade.value:els.gradeSelect.value));
  [els.competitionName,els.competitionDate,els.venue,els.bookingReference].forEach(el=>el.addEventListener('input',()=>{scheduleSave();renderHeader();}));
  els.copyPublicEntryBtn.addEventListener('click',async()=>{if(!state.publicEntryUrl)return;try{await navigator.clipboard.writeText(state.publicEntryUrl);setStatus('Public competitor entry link copied.','ok');}catch(_){els.publicEntryUrl.select();document.execCommand('copy');setStatus('Public competitor entry link copied.','ok');}});
  els.refreshEntriesBtn.addEventListener('click',()=>fetchCompetitionSetup(true));
  els.openPublicEntriesBtn.addEventListener('click',openPublicEntries);els.closePublicEntriesBtn.addEventListener('click',closePublicEntries);
  els.saveEntryControlsBtn.addEventListener('click',async()=>{const iso=localInputToIso(els.autoCloseAt.value);if(els.autoCloseAt.value&&!iso)return setStatus('That closing date/time is invalid.','warn');els.entryControlsStatus.textContent='Saving…';const ok=await saveGlobalSettings({autoCloseAt:iso});els.entryControlsStatus.textContent=ok?'Closing time saved.':'Could not save closing time.';els.entryControlsStatus.className=`status ${ok?'ok':'warn'}`;});
  els.clearScheduleBtn.addEventListener('click',async()=>{els.autoCloseAt.value='';const ok=await saveGlobalSettings({autoCloseAt:''});els.entryControlsStatus.textContent=ok?'Custom cutoff removed. Default final shutdown will apply.':'Could not update closing time.';els.entryControlsStatus.className=`status ${ok?'ok':'warn'}`;});

  els.gradesContainer.addEventListener('click',async e=>{const btn=e.target.closest('button[data-action]');if(!btn)return;const card=btn.closest('.grade-card'),g=gradeById(card?.dataset.gradeId);if(!g)return;const action=btn.dataset.action;
    if(action==='add-competitor'){const n=card.querySelector('[data-role="quick-name"]'),t=card.querySelector('[data-role="quick-town"]'),c=addCompetitorLocal(g.id,n.value,t.value);if(!c)return setStatus('Enter a name, or check that the competitor is not already listed.','warn');if(SUBMISSION_ENDPOINT){const r=await saveCompetitorCentral(g,c);if(!r.ok){g.competitors=g.competitors.filter(x=>x.id!==c.id);render();return setStatus('Could not save that competitor to the shared competition.','warn');}}render();scheduleSave();return;}
    if(action==='bulk-add'){const ta=card.querySelector('[data-role="bulk-text"]');let added=0,skipped=0;const created=[];ta.value.split(/\r?\n/).forEach(line=>{const p=parseLine(line);if(!p)return;const c=addCompetitorLocal(g.id,p.name,p.town);if(c){added++;created.push(c);}else skipped++;});if(SUBMISSION_ENDPOINT){for(const c of created){const r=await saveCompetitorCentral(g,c);if(!r.ok){g.competitors=g.competitors.filter(x=>x.id!==c.id);added--;skipped++;}}}ta.value='';render();scheduleSave();setStatus(`Added ${added}. Skipped ${skipped}.`,added?'ok':'warn');return;}
    if(action==='open-grade-public'){if(g.submitted){const choice=await dialogChoice(`Reopen ${g.name}?`,`<p>${esc(g.name)} has already been submitted. Reopening public entries does not undo that submission. A later submission would be a replacement/update.</p>`,[{label:'Cancel',value:'cancel'},{label:`Reopen ${g.name}`,value:'open',primary:true}]);if(choice!=='open')return;g.submitted=false;g.submittedAt=null;}g.publicOpen=true;if(!await saveGradeSettings(g))return setStatus('Could not reopen that grade.','warn');render();return;}
    if(action==='close-grade-public'){g.publicOpen=false;if(!await saveGradeSettings(g))return setStatus('Could not close that grade.','warn');render();return;}
    if(action==='save-limit'){const input=card.querySelector('[data-role="entry-limit"]'),raw=input.value.trim(),limit=raw?Number(raw):null;if(limit!==null&&(!Number.isInteger(limit)||limit<1))return setStatus('Entry limit must be a whole number greater than zero.','warn');g.entryLimit=limit;if(!await saveGradeSettings(g))return setStatus('Could not save the entry limit.','warn');render();setStatus(limit?`${g.name} limit set to ${limit}.`:`${g.name} entry limit removed.`,'ok');return;}
    if(action==='remove-grade'){if(g.competitors.length)return setStatus('Remove competitors from this grade before removing the grade.','warn');if(SUBMISSION_ENDPOINT){const r=await postManager({type:'speed_shear_manager_grade_remove',accessToken:state.accessToken,grade:g.name});if(!r.ok)return setStatus('Could not remove that grade.','warn');}state.grades=state.grades.filter(x=>x.id!==g.id);render();scheduleSave();return;}
    if(action==='submit-grade'){await sendSubmission([g],'grade',g.name);return;}if(action==='download-grade'){const p=submissionPayload([g],'grade');downloadJson(p,filename(p,g.name.replace(/\s+/g,'')));return;}
    const row=btn.closest('tr[data-cid]');if(!row)return;const c=g.competitors.find(x=>x.id===row.dataset.cid);if(!c)return;if(action==='toggle-check'){const previous=c.checkedIn;c.checkedIn=!c.checkedIn;if(SUBMISSION_ENDPOINT){const r=await postManager({type:'speed_shear_manager_competitor_checkin',accessToken:state.accessToken,competitorId:c.id,checkedIn:c.checkedIn});if(!r.ok){c.checkedIn=previous;setStatus('Could not save that check-in change.','warn');}}render();scheduleSave();return;}if(action==='remove-competitor'){if(SUBMISSION_ENDPOINT){const r=await postManager({type:'speed_shear_manager_competitor_remove',accessToken:state.accessToken,competitorId:c.id});if(!r.ok)return setStatus('Could not remove that competitor.','warn');}g.competitors=g.competitors.filter(x=>x.id!==c.id);render();scheduleSave();}}
  );

  els.gradesContainer.addEventListener('change',async e=>{const input=e.target.closest('input[data-edit]');if(!input)return;const card=input.closest('.grade-card'),row=input.closest('tr[data-cid]'),g=gradeById(card.dataset.gradeId),c=g?.competitors.find(x=>x.id===row.dataset.cid);if(!c)return;const previous={name:c.name,town:c.town};c[input.dataset.edit]=smartTitle(input.value);if(!c.name||g.competitors.some(x=>x.id!==c.id&&competitorKey(x)===competitorKey(c))){Object.assign(c,previous);render();return setStatus('That edit would create a blank or duplicate competitor.','warn');}if(SUBMISSION_ENDPOINT){const r=await saveCompetitorCentral(g,c);if(!r.ok){Object.assign(c,previous);setStatus('Could not save that competitor change.','warn');}}render();scheduleSave();});
  els.submitAllBtn.addEventListener('click',()=>sendSubmission(state.grades,'all','all entries'));els.downloadAllBtn.addEventListener('click',()=>{const p=submissionPayload(state.grades,'all');downloadJson(p,filename(p,'FullRoster'));});els.loadBtn.addEventListener('click',()=>els.loadFile.click());
  els.loadFile.addEventListener('change',async()=>{const f=els.loadFile.files?.[0];if(!f)return;try{const p=JSON.parse(await f.text());if(p.type!=='roster_pack'||!p.rosters)throw new Error('Unsupported file');for(const [name,list] of Object.entries(p.rosters)){let g=gradeByName(name);if(!g){await addGrade(name);g=gradeByName(name);}for(const v of(list||[])){const c=addCompetitorLocal(g.id,v.name||v,v.town||'',{source:'import'});if(c&&SUBMISSION_ENDPOINT)await saveCompetitorCentral(g,c);}}render();scheduleSave();setStatus('Roster file loaded into the shared competition.','ok');}catch(error){setStatus(error.message||'Could not load that roster file.','warn');}finally{els.loadFile.value='';}});

  try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(saved?.schemaVersion===SCHEMA_VERSION)state={...state,...saved,entrySettings:{...state.entrySettings,...(saved.entrySettings||{})},accessToken:linkToken||saved.accessToken||''};}catch(_){}
  render();if(linkToken)fetchCompetitionSetup(false);
})();
