(() => {
  const SCHEMA_VERSION = 3;
  const CONFIG_ENDPOINT = 'https://script.google.com/macros/s/AKfycbwOkoKs3Is6bSumWYe71zH2mOEZ4h0YhY-PO2JPiea2WClMs6kIMjzYtEZmqg3MlgQC-w/exec';
  const SUBMISSION_ENDPOINT = 'https://script.google.com/macros/s/AKfycbwOkoKs3Is6bSumWYe71zH2mOEZ4h0YhY-PO2JPiea2WClMs6kIMjzYtEZmqg3MlgQC-w/exec';
  const params = new URLSearchParams(location.search);
  const linkToken = params.get('access') || '';
  const STORAGE_KEY = linkToken ? `waimarinoSpeedShearEntryManagerV3_${linkToken}` : 'waimarinoSpeedShearEntryManagerV3_manual';
  const $ = id => document.getElementById(id);
  const els = {
    competitionName:$('competitionName'),competitionDate:$('competitionDate'),venue:$('venue'),bookingReference:$('bookingReference'),setupNotice:$('setupNotice'),
    settingsToggleBtn:$('settingsToggleBtn'),settingsPanel:$('settingsPanel'),publicEntryUrl:$('publicEntryUrl'),copyPublicEntryBtn:$('copyPublicEntryBtn'),refreshEntriesBtn:$('refreshEntriesBtn'),publicEntryStatus:$('publicEntryStatus'),
    openPublicEntriesBtn:$('openPublicEntriesBtn'),closePublicEntriesBtn:$('closePublicEntriesBtn'),autoCloseAt:$('autoCloseAt'),defaultCutoffNote:$('defaultCutoffNote'),saveEntryControlsBtn:$('saveEntryControlsBtn'),clearScheduleBtn:$('clearScheduleBtn'),entryControlsStatus:$('entryControlsStatus'),
    gradeSelect:$('gradeSelect'),customGrade:$('customGrade'),addGradeBtn:$('addGradeBtn'),gradesContainer:$('gradesContainer'),submitAllBtn:$('submitAllBtn'),downloadAllBtn:$('downloadAllBtn'),loadBtn:$('loadBtn'),loadFile:$('loadFile'),globalStatus:$('globalStatus'),
    dialog:$('confirmDialog'),dialogTitle:$('dialogTitle'),dialogBody:$('dialogBody'),dialogActions:$('dialogActions'),
    detailsDialog:$('detailsDialog'),detailsName:$('detailsName'),detailsPhone:$('detailsPhone'),detailsEmail:$('detailsEmail'),detailsSource:$('detailsSource'),saveDetailsBtn:$('saveDetailsBtn'),closeDetailsBtn:$('closeDetailsBtn'),savedToast:$('savedToast')
  };

  let state={schemaVersion:SCHEMA_VERSION,type:'speed_shear_entry_manager',bookingReference:'',accessToken:linkToken,publicEntryUrl:'',competition:{name:'',date:'',venue:''},entrySettings:{publicEntriesOpen:true,autoCloseAt:''},settingsOpen:false,grades:[],submissionHistory:[]};
  let saveTimer=null;
  let detailsContext=null;
  let dragState=null;

  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));}
  function clean(v){return String(v||'').trim().replace(/\s+/g,' ');}
  function key(v){return clean(v).toLowerCase();}
  function uid(){return crypto.randomUUID?.()||`id-${Date.now()}-${Math.random().toString(16).slice(2)}`;}
  function smartTitle(value){return clean(value).split(' ').map(word=>word.split('-').map(part=>{if(!part)return part;const lower=part.toLowerCase();if(/^mc[a-z]/i.test(lower))return `Mc${lower.charAt(2).toUpperCase()}${lower.slice(3)}`;return lower.charAt(0).toUpperCase()+lower.slice(1);}).join('-')).join(' ');}
  function competitorKey(c){return `${key(c.name)}|${key(c.town)}`;}
  function gradeById(id){return state.grades.find(g=>g.id===id);}
  function gradeByName(name){return state.grades.find(g=>key(g.name)===key(name));}
  function newGrade(name,meta={}){return {id:meta.id||uid(),name:clean(name),competitors:Array.isArray(meta.competitors)?meta.competitors:[],submissionVersion:Number(meta.submissionVersion||0),lastSubmittedAt:meta.lastSubmittedAt||null,publicOpen:meta.publicOpen!==false,entryLimit:Number(meta.entryLimit)>0?Number(meta.entryLimit):null,submitted:meta.submitted===true,submittedAt:meta.submittedAt||null,collapsed:meta.collapsed===true};}
  function setStatus(msg,kind=''){els.globalStatus.className=`status ${kind}`;els.globalStatus.textContent=msg||'';}
  function syncHeaderToState(){state.competition.name=clean(els.competitionName.value);state.competition.date=els.competitionDate.value||'';state.competition.venue=clean(els.venue.value);state.bookingReference=clean(els.bookingReference.value);}
  function persist(){syncHeaderToState();localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
  function scheduleSave(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>{persist();els.savedToast.classList.add('show');setTimeout(()=>els.savedToast.classList.remove('show'),900);},300);}
  function isoToLocalInput(value){if(!value)return '';const d=new Date(value);if(Number.isNaN(d.getTime()))return '';const local=new Date(d.getTime()-d.getTimezoneOffset()*60000);return local.toISOString().slice(0,16);}
  function localInputToIso(value){if(!value)return '';const d=new Date(value);return Number.isNaN(d.getTime())?'':d.toISOString();}
  function defaultFinalCutoff(){if(!state.competition.date)return '';const d=new Date(`${state.competition.date}T00:00:00`);if(Number.isNaN(d.getTime()))return '';d.setDate(d.getDate()+1);d.setHours(12,0,0,0);return d.toISOString();}
  function publicEntriesEffectivelyOpen(){if(state.entrySettings.publicEntriesOpen===false)return false;const raw=state.entrySettings.autoCloseAt||defaultFinalCutoff();if(!raw)return true;const d=new Date(raw);return Number.isNaN(d.getTime())||Date.now()<d.getTime();}
  function gradeCount(g){return g.competitors.length;}
  function confirmedCount(g){return g.competitors.filter(c=>c.checkedIn===true).length;}
  function publicCount(g){return g.competitors.filter(c=>c.source==='public-entry').length;}
  function gradeFull(g){return Boolean(g.entryLimit&&gradeCount(g)>=g.entryLimit);}
  function gradePublicOpen(g){return publicEntriesEffectivelyOpen()&&g.publicOpen!==false&&!g.submitted&&!gradeFull(g);}
  function allGradesSubmitted(){return state.grades.length>0&&state.grades.every(g=>g.submitted===true);}
  function gradeStatus(g){if(g.submitted)return 'Submitted';if(gradeFull(g))return 'Full';if(!g.publicOpen||!publicEntriesEffectivelyOpen())return 'Public Closed';return 'Public Open';}
  function formatSubmitted(value){if(!value)return '';const d=new Date(value);return Number.isNaN(d.getTime())?'':d.toLocaleString('en-NZ',{dateStyle:'medium',timeStyle:'short'});}
  function iconSvg(name){
    const paths={
      up:'<path d="M6 15l6-6 6 6"/>',
      down:'<path d="M6 9l6 6 6-6"/>',
      grip:'<circle cx="8" cy="7" r="1" fill="currentColor" stroke="none"/><circle cx="16" cy="7" r="1" fill="currentColor" stroke="none"/><circle cx="8" cy="12" r="1" fill="currentColor" stroke="none"/><circle cx="16" cy="12" r="1" fill="currentColor" stroke="none"/><circle cx="8" cy="17" r="1" fill="currentColor" stroke="none"/><circle cx="16" cy="17" r="1" fill="currentColor" stroke="none"/>',
      collapse:'<path d="M7 14l5-5 5 5"/>',
      expand:'<path d="M7 10l5 5 5-5"/>'
    };
    return `<svg viewBox="0 0 24 24" aria-hidden="true">${paths[name]||''}</svg>`;
  }

  function dialogChoice(title,html,choices){return new Promise(resolve=>{els.dialogTitle.textContent=title;els.dialogBody.innerHTML=html;els.dialogActions.innerHTML='';let resolved=false;const finish=v=>{if(resolved)return;resolved=true;resolve(v);};choices.forEach(choice=>{const b=document.createElement('button');b.type='button';b.textContent=choice.label;b.className=choice.primary?'primary':'secondary';b.addEventListener('click',()=>{els.dialog.close();finish(choice.value);},{once:true});els.dialogActions.appendChild(b);});els.dialog.addEventListener('cancel',()=>finish(null),{once:true});els.dialog.showModal();});}

  function renderHeader(){
    els.competitionName.value=state.competition.name||'';els.competitionDate.value=state.competition.date||'';els.venue.value=state.competition.venue||'';els.bookingReference.value=state.bookingReference||'';
    els.settingsPanel.classList.toggle('hidden',!state.settingsOpen);els.settingsToggleBtn.setAttribute('aria-expanded',state.settingsOpen?'true':'false');els.settingsToggleBtn.textContent=state.settingsOpen?'Close Settings':'Settings';
    els.publicEntryUrl.value=state.publicEntryUrl||'';els.autoCloseAt.value=isoToLocalInput(state.entrySettings.autoCloseAt||'');
    const finalCutoff=defaultFinalCutoff();els.defaultCutoffNote.textContent=state.entrySettings.autoCloseAt?'A custom closing time is set.':(finalCutoff?'No custom cutoff set. The default final shutdown is 12 hours after the competition day ends.':'If left blank, the public form automatically shuts down 12 hours after the competition day ends.');
    const open=publicEntriesEffectivelyOpen();els.publicEntryStatus.textContent=`Public entries: ${open?'Open':'Closed'}`;els.publicEntryStatus.className=`badge ${open?'green':'closed'}`;els.openPublicEntriesBtn.disabled=open&&state.entrySettings.publicEntriesOpen!==false;els.closePublicEntriesBtn.disabled=state.entrySettings.publicEntriesOpen===false;
  }

  function render(){
    renderHeader();
    if(!state.grades.length){els.gradesContainer.innerHTML='<p class="status">No grades or events added yet.</p>';return;}
    els.gradesContainer.innerHTML=state.grades.map((g,index)=>{
      const count=gradeCount(g),confirmed=confirmedCount(g),status=gradeStatus(g),remaining=g.entryLimit?Math.max(0,g.entryLimit-count):null;
      const rows=g.competitors.map((c,i)=>`<tr data-cid="${esc(c.id)}"><td>${i+1}</td><td><input data-edit="name" value="${esc(c.name)}"></td><td><input data-edit="town" value="${esc(c.town)}"></td><td><button class="confirm-btn ${c.checkedIn?'confirmed':''}" data-action="toggle-confirm">${c.checkedIn?'Confirmed':'Not Confirmed'}</button></td><td><button class="details-btn" data-action="details">Details</button></td><td><button class="secondary" data-action="remove-competitor">Remove</button></td></tr>`).join('');
      const statusClass=g.submitted?'submitted':gradeFull(g)?'full':gradePublicOpen(g)?'green':'closed';
      const limitText=g.entryLimit?`${count}/${g.entryLimit}${remaining?` — ${remaining} place${remaining===1?'':'s'} left`:''}`:`${count} entered — no limit`;
      const submittedMeta=g.submitted?`<span class="submission-meta">Submitted${g.submittedAt?` ${esc(formatSubmitted(g.submittedAt))}`:''}${g.submissionVersion?` · Version ${g.submissionVersion}`:''}</span>`:'';
      return `<article class="grade-card ${g.submitted?'submitted':gradeFull(g)?'full':''} ${g.collapsed?'collapsed':''}" data-grade-id="${esc(g.id)}">
        <div class="grade-summary">
          <div class="grade-title-wrap"><div class="grade-title-row"><h3>${esc(g.name)}</h3><span class="badge ${statusClass}">${esc(status)}</span></div><div class="badges"><span class="badge">Total: ${count}</span><span class="badge green">Confirmed: ${confirmed}</span>${publicCount(g)?`<span class="badge public">Online: ${publicCount(g)}</span>`:''}<span class="badge ${gradeFull(g)?'full':''}">${esc(limitText)}</span></div></div>
          <div class="card-tools">
            <button type="button" class="icon-btn drag-handle" data-drag-handle aria-label="Drag ${esc(g.name)} to reorder" title="Drag to reorder">${iconSvg('grip')}</button>
            <button type="button" class="icon-btn" data-action="move-up" ${index===0?'disabled':''} aria-label="Move ${esc(g.name)} up" title="Move up">${iconSvg('up')}</button>
            <button type="button" class="icon-btn" data-action="move-down" ${index===state.grades.length-1?'disabled':''} aria-label="Move ${esc(g.name)} down" title="Move down">${iconSvg('down')}</button>
            <button type="button" class="icon-btn" data-action="toggle-collapse" aria-expanded="${g.collapsed?'false':'true'}" aria-label="${g.collapsed?'Expand':'Collapse'} ${esc(g.name)}" title="${g.collapsed?'Expand':'Collapse'}">${iconSvg(g.collapsed?'expand':'collapse')}</button>
          </div>
        </div>
        <div class="grade-body">
          <div class="grade-primary-action"><button class="submit-grade-primary ${g.submitted?'submitted':''}" data-action="submit-grade">${g.submitted?'Update Closed Entries':'Close Entries'}</button>${submittedMeta}</div>
          <div class="grade-secondary-actions"><button class="secondary" data-action="download-grade">Download JSON</button><button class="secondary" data-action="download-pdf">Download PDF</button><button class="secondary" data-action="remove-grade">Remove Grade</button></div>
          <div class="grade-public-controls"><div><label>Public entries for ${esc(g.name)}</label><div class="entry-control-actions"><button data-action="open-grade-public" ${g.submitted?'disabled':''}>Open</button><button class="secondary" data-action="close-grade-public">Close</button><button class="help-link" data-action="grade-help" type="button">How this works</button></div></div>
          <div><label>Optional entry limit</label><div class="limit-row"><input data-role="entry-limit" type="number" min="1" step="1" value="${g.entryLimit||''}" placeholder="No limit"><button class="secondary" data-action="save-limit">Save</button></div></div></div>
          <div class="quick-row"><input data-role="quick-name" placeholder="Competitor name"><input data-role="quick-town" placeholder="Hometown (optional)"><button data-action="add-competitor">Add Competitor</button></div>
          <div class="bulk"><details><summary><strong>Add a list of names</strong></summary><textarea data-role="bulk-text" placeholder="One competitor per line. Name or Name, Town"></textarea><div class="entry-control-actions"><button data-action="bulk-add">Add From List</button></div></details></div>
          <table class="competitor-table"><thead><tr><th>#</th><th>Name</th><th>Town</th><th>Checked / Paid</th><th>Details</th><th>Remove</th></tr></thead><tbody>${rows||'<tr><td colspan="6">No competitors added yet.</td></tr>'}</tbody></table>
        </div>
      </article>`;
    }).join('');
  }

  function updateConfirmationUi(card,g,btn,c){
    btn.classList.toggle('confirmed',c.checkedIn===true);
    btn.textContent=c.checkedIn?'Confirmed':'Not Confirmed';
    const badge=[...card.querySelectorAll('.badges .badge')].find(node=>/^Confirmed:\s*/i.test(String(node.textContent||'').trim()));
    if(badge)badge.textContent=`Confirmed: ${confirmedCount(g)}`;
  }

  function highlightMoved(gradeId){requestAnimationFrame(()=>{const card=els.gradesContainer.querySelector(`.grade-card[data-grade-id="${CSS.escape(gradeId)}"]`);if(!card)return;card.classList.add('moved-highlight');setTimeout(()=>card.classList.remove('moved-highlight'),1400);});}
  async function postManager(payload){if(!SUBMISSION_ENDPOINT)return {ok:false,offline:true};try{await fetch(SUBMISSION_ENDPOINT,{method:'POST',mode:'no-cors',cache:'no-store',headers:{'Content-Type':'text/plain;charset=UTF-8'},body:JSON.stringify(payload)});return {ok:true};}catch(error){return {ok:false,error};}}
  async function saveCompetitorCentral(g,c){return postManager({type:'speed_shear_manager_competitor_upsert',accessToken:state.accessToken,competitor:{id:c.id,grade:g.name,name:c.name,town:c.town,phone:c.phone||'',email:c.email||'',source:c.source||'manual',checkedIn:c.checkedIn===true,createdAt:c.createdAt||''}});}
  function addCompetitorLocal(gradeId,name,town='',extra={}){const g=gradeById(gradeId);if(!g)return null;const c={id:extra.id||uid(),name:smartTitle(name),town:smartTitle(town),phone:clean(extra.phone),email:clean(extra.email),source:extra.source||'manual',checkedIn:Boolean(extra.checkedIn),createdAt:extra.createdAt||new Date().toISOString()};if(!c.name||g.competitors.some(x=>competitorKey(x)===competitorKey(c)))return null;g.competitors.push(c);return c;}
  function parseLine(line){const text=clean(line);if(!text)return null;const comma=text.indexOf(',');if(comma>=0)return{name:clean(text.slice(0,comma)),town:clean(text.slice(comma+1))};const tab=text.match(/^(.*?)\t+(.*)$/);if(tab)return{name:clean(tab[1]),town:clean(tab[2])};const dash=text.match(/^(.*?)\s+[\-–—]\s+(.*)$/);if(dash)return{name:clean(dash[1]),town:clean(dash[2])};return{name:text,town:''};}

  async function addGrade(name){name=clean(name);if(!name)return;if(gradeByName(name))return setStatus(`${name} already exists.`,'warn');if(SUBMISSION_ENDPOINT){const r=await postManager({type:'speed_shear_manager_grade_add',accessToken:state.accessToken,grade:name});if(!r.ok)return setStatus('Could not add that grade to the shared competition.','warn');}state.grades.push(newGrade(name));els.customGrade.value='';render();scheduleSave();}
  async function saveGlobalSettings(settings){state.entrySettings={...state.entrySettings,...settings};render();persist();if(SUBMISSION_ENDPOINT){const r=await postManager({type:'speed_shear_manager_entry_settings',accessToken:state.accessToken,entrySettings:{...state.entrySettings}});if(!r.ok)return false;await fetchCompetitionSetup(false);}return true;}
  async function saveGradeSettings(g){if(SUBMISSION_ENDPOINT){const r=await postManager({type:'speed_shear_manager_grade_settings',accessToken:state.accessToken,grade:g.name,gradeSettings:{publicOpen:g.publicOpen!==false,entryLimit:g.entryLimit}});if(!r.ok)return false;}scheduleSave();return true;}
  async function saveGradeOrder(){scheduleSave();if(SUBMISSION_ENDPOINT){const r=await postManager({type:'speed_shear_manager_grade_reorder',accessToken:state.accessToken,grades:state.grades.map(g=>g.name)});if(!r.ok){setStatus('Could not save the new grade order to the shared competition.','warn');return false;}}return true;}

  function submissionPayload(grades,mode){syncHeaderToState();return{schemaVersion:2,type:'speed_shear_roster_submission',bookingReference:state.bookingReference,accessToken:state.accessToken,competition:{...state.competition},submission:{mode,submittedAt:new Date().toISOString()},grades:Object.fromEntries(grades.map(g=>[g.name,g.competitors.filter(c=>c.checkedIn).map(c=>({name:c.name,town:c.town||''}))]))};}
  function unconfirmed(grades){return grades.flatMap(g=>g.competitors.filter(c=>!c.checkedIn).map(c=>({grade:g.name,name:c.name})));}
  async function confirmSubmission(grades,label){const missing=unconfirmed(grades),included=grades.reduce((n,g)=>n+confirmedCount(g),0);if(!included){setStatus('There are no confirmed competitors to close and send.','warn');return false;}if(!missing.length)return true;const choice=await dialogChoice('Some competitors are not confirmed',`<p><strong>${included} confirmed competitor${included===1?'':'s'} will be included in the roster sent to Waimarino Shears.</strong></p><p>${missing.length} competitor${missing.length===1?' is':'s are'} not confirmed and will not be included:</p><ul>${missing.map(x=>`<li><strong>${esc(x.name)}</strong>${grades.length>1?` — ${esc(x.grade)}`:''}</li>`).join('')}</ul>`,[{label:'Go Back',value:'cancel'},{label:'Close Entries Anyway',value:'submit',primary:true}]);return choice==='submit';}
  function filename(payload,suffix){const comp=(payload.competition.name||'Competition').replace(/[^a-z0-9]+/gi,'_').replace(/^_|_$/g,'');return `${comp}_${payload.bookingReference||'NoRef'}_${suffix}.json`;}
  function downloadJson(payload,name){const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}
  async function promptAllSubmitted(){const choice=await dialogChoice('All grades and events closed','<p><strong>All grade and event entries have now been closed and sent.</strong></p><p>There are no remaining grades available for public entry. Would you like to close the public competitor entry link now?</p>',[{label:'Keep Link Open',value:'keep'},{label:'Close Public Entries',value:'close',primary:true}]);if(choice==='close'){await saveGlobalSettings({publicEntriesOpen:false});setStatus('All entries closed. Public entries closed.','ok');}}
  async function sendSubmission(grades,mode,label){if(!await confirmSubmission(grades,label))return;const payload=submissionPayload(grades,mode);if(SUBMISSION_ENDPOINT){const r=await postManager(payload);if(!r.ok){downloadJson(payload,filename(payload,mode==='all'?'AllEntries':label));return setStatus('Could not send the confirmed roster. Backup JSON downloaded.','warn');}setStatus(`${label==='all entries'?'All entries':`${label} entries`} closed and confirmed roster sent to Waimarino Shears.`,'ok');}else{downloadJson(payload,filename(payload,mode==='all'?'AllEntries':label));setStatus('Backend is not deployed yet. JSON downloaded for testing; PDF generation starts when Apps Script is connected.','warn');}
    const now=new Date().toISOString();grades.forEach(g=>{g.submissionVersion=(g.submissionVersion||0)+1;g.lastSubmittedAt=now;g.submitted=true;g.submittedAt=now;g.publicOpen=false;});state.submissionHistory.push({mode,grades:grades.map(g=>g.name),submittedAt:now});render();scheduleSave();if(allGradesSubmitted())await promptAllSubmitted();}
  async function fetchCompetitionSetup(showMessage=false){const token=state.accessToken||linkToken;if(!token)return;if(!CONFIG_ENDPOINT){if(showMessage)setStatus('The shared backend is not connected yet.','warn');return;}try{const r=await fetch(`${CONFIG_ENDPOINT}?action=entry-manager&access=${encodeURIComponent(token)}`,{cache:'no-store'}),setup=await r.json();if(!setup.ok)throw new Error(setup.error||'Could not load competition');applySetup(setup);if(showMessage)setStatus('Shared competition state refreshed.','ok');}catch(_){setStatus('Could not refresh this competition.','warn');}}
  function applySetup(setup){state.bookingReference=setup.bookingReference||state.bookingReference;state.accessToken=setup.accessToken||state.accessToken||linkToken;state.publicEntryUrl=setup.competitorEntryUrl||state.publicEntryUrl;state.competition={...state.competition,...(setup.competition||{})};state.entrySettings={publicEntriesOpen:setup.entrySettings?.publicEntriesOpen!==false,autoCloseAt:setup.entrySettings?.autoCloseAt||''};const old=new Map(state.grades.map(g=>[key(g.name),g]));const names=Array.isArray(setup.grades)?setup.grades:Object.keys(setup.competitionSetup?.events||{});state.grades=names.map(name=>{const previous=old.get(key(name))||{},remote=setup.gradeSettings?.[name]||{};return newGrade(name,{...previous,...remote,competitors:[],entryLimit:remote.entryLimit??previous.entryLimit,publicOpen:remote.publicOpen??previous.publicOpen,submitted:remote.submitted??previous.submitted,submittedAt:remote.submittedAt??previous.submittedAt,collapsed:previous.collapsed===true});});(setup.competitors||[]).forEach(entry=>{let g=gradeByName(entry.grade);if(!g){g=newGrade(entry.grade);state.grades.push(g);}addCompetitorLocal(g.id,entry.name,entry.town,{...entry,checkedIn:entry.checkedIn===true,source:entry.source||'manual'});});els.setupNotice.textContent='Competition details, entries, grade status and confirmation state are loaded from the shared competition record.';els.setupNotice.classList.remove('hidden');render();persist();}

  async function closePublicEntries(){const choice=await dialogChoice('Close public entries','<p>Choose how you want to close the public competitor entry link.</p>',[{label:'Cancel — Leave Open',value:'cancel'},{label:'Close Temporarily — Keep Scheduled Cutoff',value:'temporary'},{label:'Close and Cancel Custom Cutoff',value:'permanent',primary:true}]);if(choice==='temporary'&&await saveGlobalSettings({publicEntriesOpen:false}))setStatus('Public entries temporarily closed. Scheduled cutoff kept.','ok');if(choice==='permanent'&&await saveGlobalSettings({publicEntriesOpen:false,autoCloseAt:''}))setStatus('Public entries closed. Custom cutoff removed.','ok');}
  async function openPublicEntries(){const cutoff=state.entrySettings.autoCloseAt;const choice=await dialogChoice('Open public entries',cutoff?`<p>Public entries will reopen. Your scheduled closing time of <strong>${esc(new Date(cutoff).toLocaleString('en-NZ'))}</strong> will remain in place.</p>`:'<p>Public entries will reopen. The default final shutdown remains in place.</p>',[{label:'Cancel',value:'cancel'},{label:'Open Public Entries',value:'open',primary:true}]);if(choice==='open'&&await saveGlobalSettings({publicEntriesOpen:true}))setStatus('Public entries reopened.','ok');}

  function openDetails(g,c){detailsContext={g,c};els.detailsName.textContent=c.name;els.detailsPhone.value=c.phone||'';els.detailsEmail.value=c.email||'';els.detailsSource.textContent=c.source==='public-entry'?'Contact details supplied through the public competitor entry form.':'Manual entry — contact details are optional.';els.detailsDialog.showModal();}
  async function saveDetails(){if(!detailsContext)return;const {g,c}=detailsContext,old={phone:c.phone,email:c.email};c.phone=clean(els.detailsPhone.value);c.email=clean(els.detailsEmail.value).toLowerCase();if(SUBMISSION_ENDPOINT){const r=await saveCompetitorCentral(g,c);if(!r.ok){Object.assign(c,old);return setStatus('Could not save competitor details.','warn');}}els.detailsDialog.close();render();scheduleSave();setStatus('Competitor details saved.','ok');}

  function startDrag(e){const handle=e.target.closest('[data-drag-handle]');if(!handle||dragState||e.button>0)return;const card=handle.closest('.grade-card');if(!card)return;dragState={pointerId:e.pointerId,gradeId:card.dataset.gradeId,card,handle,startY:e.clientY,moved:false};card.classList.add('dragging');try{handle.setPointerCapture(e.pointerId);}catch(_){}e.preventDefault();}
  function moveDrag(e){if(!dragState||e.pointerId!==dragState.pointerId)return;const {card}=dragState;if(Math.abs(e.clientY-dragState.startY)>5)dragState.moved=true;if(!dragState.moved)return;const others=[...els.gradesContainer.querySelectorAll('.grade-card')].filter(x=>x!==card);let placed=false;for(const other of others){const r=other.getBoundingClientRect();if(e.clientY<r.top+r.height/2){els.gradesContainer.insertBefore(card,other);placed=true;break;}}if(!placed)els.gradesContainer.appendChild(card);e.preventDefault();}
  async function endDrag(e){if(!dragState||e.pointerId!==dragState.pointerId)return;const {card,handle,gradeId,moved}=dragState;dragState=null;card.classList.remove('dragging');try{handle.releasePointerCapture(e.pointerId);}catch(_){}if(!moved)return;const ids=[...els.gradesContainer.querySelectorAll('.grade-card')].map(node=>node.dataset.gradeId);const byId=new Map(state.grades.map(g=>[g.id,g]));state.grades=ids.map(id=>byId.get(id)).filter(Boolean);await saveGradeOrder();highlightMoved(gradeId);}

  els.settingsToggleBtn.addEventListener('click',()=>{state.settingsOpen=!state.settingsOpen;renderHeader();scheduleSave();});
  document.addEventListener('click',e=>{const help=e.target.closest('[data-help="public-close"]');if(!help)return;dialogChoice('Public entry controls','<p>Closing the public link does not stop staff from adding competitors manually. A temporary closure keeps your scheduled cutoff so you can reopen the link later.</p><p>If no custom closing time is set, the public link automatically shuts down 12 hours after the competition day ends.</p>',[{label:'Close',value:'close',primary:true}]);});
  els.gradeSelect.addEventListener('change',()=>els.customGrade.classList.toggle('hidden',els.gradeSelect.value!=='__custom__'));
  els.addGradeBtn.addEventListener('click',()=>addGrade(els.gradeSelect.value==='__custom__'?els.customGrade.value:els.gradeSelect.value));
  [els.competitionName,els.competitionDate,els.venue,els.bookingReference].forEach(el=>el.addEventListener('input',()=>{scheduleSave();renderHeader();}));
  els.copyPublicEntryBtn.addEventListener('click',async()=>{if(!state.publicEntryUrl)return setStatus('The public entry link will be created when the backend is connected.','warn');try{await navigator.clipboard.writeText(state.publicEntryUrl);setStatus('Public competitor entry link copied.','ok');}catch(_){setStatus('Could not copy the link automatically.','warn');}});
  els.refreshEntriesBtn.addEventListener('click',()=>fetchCompetitionSetup(true));els.openPublicEntriesBtn.addEventListener('click',openPublicEntries);els.closePublicEntriesBtn.addEventListener('click',closePublicEntries);
  els.saveEntryControlsBtn.addEventListener('click',async()=>{const iso=localInputToIso(els.autoCloseAt.value);if(els.autoCloseAt.value&&!iso)return setStatus('That closing date/time is invalid.','warn');const ok=await saveGlobalSettings({autoCloseAt:iso});els.entryControlsStatus.textContent=ok?'Closing time saved.':'Could not save closing time.';els.entryControlsStatus.className=`status ${ok?'ok':'warn'}`;});
  els.clearScheduleBtn.addEventListener('click',async()=>{els.autoCloseAt.value='';const ok=await saveGlobalSettings({autoCloseAt:''});els.entryControlsStatus.textContent=ok?'Custom cutoff removed. Default final shutdown will apply.':'Could not update closing time.';els.entryControlsStatus.className=`status ${ok?'ok':'warn'}`;});

  els.gradesContainer.addEventListener('pointerdown',startDrag);
  window.addEventListener('pointermove',moveDrag,{passive:false});
  window.addEventListener('pointerup',endDrag);
  window.addEventListener('pointercancel',endDrag);

  els.gradesContainer.addEventListener('click',async e=>{const btn=e.target.closest('button[data-action]');if(!btn)return;const card=btn.closest('.grade-card'),g=gradeById(card?.dataset.gradeId);if(!g)return;const action=btn.dataset.action;
    if(action==='toggle-collapse'){g.collapsed=!g.collapsed;render();scheduleSave();return;}
    if(action==='move-up'||action==='move-down'){const i=state.grades.findIndex(x=>x.id===g.id),j=action==='move-up'?i-1:i+1;if(j<0||j>=state.grades.length)return;[state.grades[i],state.grades[j]]=[state.grades[j],state.grades[i]];render();await saveGradeOrder();highlightMoved(g.id);return;}
    if(action==='grade-help'){await dialogChoice(`${g.name} grade public entries`,`<p>Public entries for this grade can be opened or closed independently.</p><p>Closing ${esc(g.name)} entries sends the confirmed roster and automatically closes public entries for this grade. No further public entries can be accepted.</p><p>Manual staff entry remains available at all times.</p>`,[{label:'Close',value:'close',primary:true}]);return;}
    if(action==='add-competitor'){const n=card.querySelector('[data-role="quick-name"]'),t=card.querySelector('[data-role="quick-town"]'),c=addCompetitorLocal(g.id,n.value,t.value);if(!c)return setStatus('Enter a name, or check that the competitor is not already listed.','warn');if(SUBMISSION_ENDPOINT){const r=await saveCompetitorCentral(g,c);if(!r.ok){g.competitors=g.competitors.filter(x=>x.id!==c.id);render();return setStatus('Could not save that competitor.','warn');}}render();scheduleSave();return;}
    if(action==='bulk-add'){const ta=card.querySelector('[data-role="bulk-text"]');let added=0,skipped=0;const created=[];ta.value.split(/\r?\n/).forEach(line=>{const p=parseLine(line);if(!p)return;const c=addCompetitorLocal(g.id,p.name,p.town);if(c){added++;created.push(c);}else skipped++;});if(SUBMISSION_ENDPOINT){for(const c of created){const r=await saveCompetitorCentral(g,c);if(!r.ok){g.competitors=g.competitors.filter(x=>x.id!==c.id);added--;skipped++;}}}ta.value='';render();scheduleSave();setStatus(`Added ${added}. Skipped ${skipped}.`,added?'ok':'warn');return;}
    if(action==='open-grade-public'){if(g.submitted){const choice=await dialogChoice(`Reopen ${g.name}?`,`<p>${esc(g.name)} entries have already been submitted. Reopening public entries does not undo that submission. A later submission will be an updated entry submission.</p>`,[{label:'Cancel',value:'cancel'},{label:`Reopen ${g.name}`,value:'open',primary:true}]);if(choice!=='open')return;g.submitted=false;g.submittedAt=null;}g.publicOpen=true;if(!await saveGradeSettings(g))return setStatus('Could not reopen that grade.','warn');render();return;}
    if(action==='close-grade-public'){g.publicOpen=false;if(!await saveGradeSettings(g))return setStatus('Could not close that grade.','warn');render();return;}
    if(action==='save-limit'){const input=card.querySelector('[data-role="entry-limit"]'),raw=input.value.trim(),limit=raw?Number(raw):null;if(limit!==null&&(!Number.isInteger(limit)||limit<1))return setStatus('Entry limit must be a whole number greater than zero.','warn');g.entryLimit=limit;if(!await saveGradeSettings(g))return setStatus('Could not save the entry limit.','warn');render();setStatus(limit?`${g.name} limit set to ${limit}.`:`${g.name} entry limit removed.`,'ok');return;}
    if(action==='remove-grade'){if(g.competitors.length)return setStatus('Remove competitors from this grade before removing the grade.','warn');if(SUBMISSION_ENDPOINT){const r=await postManager({type:'speed_shear_manager_grade_remove',accessToken:state.accessToken,grade:g.name});if(!r.ok)return setStatus('Could not remove that grade.','warn');}state.grades=state.grades.filter(x=>x.id!==g.id);render();scheduleSave();return;}
    if(action==='submit-grade'){await sendSubmission([g],'grade',g.name);return;}
    if(action==='download-grade'){const p=submissionPayload([g],'grade');downloadJson(p,filename(p,g.name.replace(/\s+/g,'')));return;}
    if(action==='download-pdf'){setStatus('The styled PDF is generated with the submission when the Google Apps Script backend is connected.','warn');return;}
    const row=btn.closest('tr[data-cid]');if(!row)return;const c=g.competitors.find(x=>x.id===row.dataset.cid);if(!c)return;
    if(action==='toggle-confirm'){const previous=c.checkedIn;c.checkedIn=!c.checkedIn;updateConfirmationUi(card,g,btn,c);scheduleSave();if(SUBMISSION_ENDPOINT){const r=await postManager({type:'speed_shear_manager_competitor_checkin',accessToken:state.accessToken,competitorId:c.id,checkedIn:c.checkedIn});if(!r.ok){c.checkedIn=previous;updateConfirmationUi(card,g,btn,c);scheduleSave();setStatus('Could not save that confirmation change.','warn');}}return;}
    if(action==='details'){openDetails(g,c);return;}
    if(action==='remove-competitor'){if(SUBMISSION_ENDPOINT){const r=await postManager({type:'speed_shear_manager_competitor_remove',accessToken:state.accessToken,competitorId:c.id});if(!r.ok)return setStatus('Could not remove that competitor.','warn');}g.competitors=g.competitors.filter(x=>x.id!==c.id);render();scheduleSave();return;}
  });

  els.gradesContainer.addEventListener('change',async e=>{const input=e.target.closest('input[data-edit]');if(!input)return;const card=input.closest('.grade-card'),row=input.closest('tr[data-cid]'),g=gradeById(card.dataset.gradeId),c=g?.competitors.find(x=>x.id===row.dataset.cid);if(!c)return;const previous={name:c.name,town:c.town};c[input.dataset.edit]=smartTitle(input.value);if(!c.name||g.competitors.some(x=>x.id!==c.id&&competitorKey(x)===competitorKey(c))){Object.assign(c,previous);render();return setStatus('That edit would create a blank or duplicate competitor.','warn');}if(SUBMISSION_ENDPOINT){const r=await saveCompetitorCentral(g,c);if(!r.ok){Object.assign(c,previous);setStatus('Could not save that competitor change.','warn');}}render();scheduleSave();});
  els.saveDetailsBtn.addEventListener('click',saveDetails);els.closeDetailsBtn.addEventListener('click',()=>els.detailsDialog.close());
  els.submitAllBtn.addEventListener('click',()=>sendSubmission(state.grades,'all','all entries'));els.downloadAllBtn.addEventListener('click',()=>{const p=submissionPayload(state.grades,'all');downloadJson(p,filename(p,'FullRoster'));});els.loadBtn.addEventListener('click',()=>els.loadFile.click());
  els.loadFile.addEventListener('change',async()=>{const f=els.loadFile.files?.[0];if(!f)return;try{const p=JSON.parse(await f.text());if(p.type!=='roster_pack'||!p.rosters)throw new Error('Unsupported file');for(const [name,list] of Object.entries(p.rosters)){let g=gradeByName(name);if(!g){await addGrade(name);g=gradeByName(name);}for(const v of(list||[])){const c=addCompetitorLocal(g.id,v.name||v,v.town||'',{source:'import'});if(c&&SUBMISSION_ENDPOINT)await saveCompetitorCentral(g,c);}}render();scheduleSave();setStatus('Roster file loaded.','ok');}catch(error){setStatus(error.message||'Could not load that roster file.','warn');}finally{els.loadFile.value='';}});

  try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(saved&&Array.isArray(saved.grades)){state={...state,...saved,schemaVersion:SCHEMA_VERSION,entrySettings:{...state.entrySettings,...(saved.entrySettings||{})},accessToken:linkToken||saved.accessToken||'',grades:saved.grades.map(g=>newGrade(g.name,g))};}}catch(_){}
  render();if(linkToken)fetchCompetitionSetup(false);
})();