const ENTRY_MANAGER_SETTINGS = {
  receiverEmail: 'Waimarinoshears@gmail.com',
  senderName: 'Waimarino Shears Entry Manager',
  driveFolderName: 'Waimarino Speed Shear Entry Manager',
  publicBaseUrl: 'https://turiedmonds.github.io/speed-shear-roster-builder/',
  competitorEntryPath: 'competitor-entry.html',
  schemaVersion: 2
};

function entryManagerCreateCompetition_(pack) {
  if (!pack || !pack.identity || !pack.identity.bookingReference) throw new Error('Booking Reference is required.');
  const reference = String(pack.identity.bookingReference).trim();
  const lock = LockService.getScriptLock(); lock.waitLock(30000);
  try {
    const properties = PropertiesService.getScriptProperties();
    const existingId = properties.getProperty('entryManagerReference_' + reference);
    if (existingId) {
      try {
        const existing = JSON.parse(DriveApp.getFileById(existingId).getBlob().getDataAsString());
        entryManagerNormaliseRecord_(existing);
        return entryManagerLinksFromRecord_(existing, existingId);
      } catch (error) { console.warn('Existing Entry Manager record could not be read. Recreating it.', error); }
    }
    const managerToken = entryManagerToken_(), publicEntryToken = entryManagerToken_(), setup = pack.competitionSetup || {}, grades = Object.keys(setup.events || {});
    const record = {
      schemaVersion:ENTRY_MANAGER_SETTINGS.schemaVersion,type:'speed_shear_entry_manager_competition',bookingReference:reference,managerToken,publicEntryToken,createdAt:new Date().toISOString(),
      competition:{name:String(pack.booking && pack.booking.competitionName || ''),date:String(pack.booking && pack.booking.competitionDate || ''),venue:String(pack.booking && pack.booking.venue || '')},
      organiser:{name:String(pack.booking && pack.booking.contactPerson || ''),email:String(pack.booking && pack.booking.email || ''),phone:String(pack.booking && pack.booking.phone || '')},
      grades,
      gradeSettings:{},
      competitionSetup:{events:JSON.parse(JSON.stringify(setup.events || {})),program:JSON.parse(JSON.stringify(setup.program || []))},
      entrySettings:{publicEntriesOpen:true,autoCloseAt:'',updatedAt:new Date().toISOString()},competitors:[],submissions:[]
    };
    grades.forEach(g => record.gradeSettings[g] = entryManagerNewGradeSettings_());
    const blob = Utilities.newBlob(JSON.stringify(record,null,2),'application/json',reference+'_EntryManager.json');
    const file = entryManagerFolder_().createFile(blob);
    properties.setProperty('entryManagerToken_'+managerToken,file.getId());properties.setProperty('entryPublicToken_'+publicEntryToken,file.getId());properties.setProperty('entryManagerReference_'+reference,file.getId());
    return entryManagerLinksFromRecord_(record,file.getId());
  } finally { lock.releaseLock(); }
}

function entryManagerNewGradeSettings_() { return {publicOpen:true,entryLimit:null,submitted:false,submittedAt:''}; }
function entryManagerNormaliseRecord_(record) {
  record.grades=Array.isArray(record.grades)?record.grades:[];record.competitors=Array.isArray(record.competitors)?record.competitors:[];record.submissions=Array.isArray(record.submissions)?record.submissions:[];
  record.entrySettings=record.entrySettings&&typeof record.entrySettings==='object'?record.entrySettings:{};if(record.entrySettings.publicEntriesOpen==null)record.entrySettings.publicEntriesOpen=true;if(record.entrySettings.autoCloseAt==null)record.entrySettings.autoCloseAt='';
  record.gradeSettings=record.gradeSettings&&typeof record.gradeSettings==='object'?record.gradeSettings:{};
  record.grades.forEach(g=>{const current=record.gradeSettings[g]&&typeof record.gradeSettings[g]==='object'?record.gradeSettings[g]:{};record.gradeSettings[g]={publicOpen:current.publicOpen!==false,entryLimit:Number(current.entryLimit)>0?Number(current.entryLimit):null,submitted:current.submitted===true,submittedAt:String(current.submittedAt||'')};});
  record.competitors.forEach(item=>{if(item.checkedIn==null)item.checkedIn=false;if(!item.source)item.source='public-entry';});return record;
}
function entryManagerLinksFromRecord_(record,fileId){return{bookingReference:record.bookingReference,managerToken:record.managerToken,publicEntryToken:record.publicEntryToken,entryManagerUrl:entryManagerUrl_(record.managerToken),competitorEntryUrl:entryManagerCompetitorUrl_(record.publicEntryToken),fileId:fileId||''};}
function entryManagerToken_(){return Utilities.getUuid().replace(/-/g,'')+Utilities.getUuid().replace(/-/g,'');}
function entryManagerFolder_(){const folders=DriveApp.getFoldersByName(ENTRY_MANAGER_SETTINGS.driveFolderName);return folders.hasNext()?folders.next():DriveApp.createFolder(ENTRY_MANAGER_SETTINGS.driveFolderName);}
function entryManagerUrl_(token){return ENTRY_MANAGER_SETTINGS.publicBaseUrl+'?access='+encodeURIComponent(token);}
function entryManagerCompetitorUrl_(token){return ENTRY_MANAGER_SETTINGS.publicBaseUrl+ENTRY_MANAGER_SETTINGS.competitorEntryPath+'?entry='+encodeURIComponent(token);}
function entryManagerReadByManagerToken_(token){return entryManagerReadByProperty_('entryManagerToken_',token,'managerToken');}
function entryManagerReadByPublicToken_(token){return entryManagerReadByProperty_('entryPublicToken_',token,'publicEntryToken');}
function entryManagerReadByProperty_(prefix,token,field){const clean=String(token||'').trim();if(!clean)throw new Error('Access token is missing.');const id=PropertiesService.getScriptProperties().getProperty(prefix+clean);if(!id)throw new Error('Competition link was not found.');const file=DriveApp.getFileById(id),record=JSON.parse(file.getBlob().getDataAsString());if(record[field]!==clean)throw new Error('Competition link is invalid.');entryManagerNormaliseRecord_(record);return{record,file};}
function entryManagerSaveRecord_(found){found.file.setContent(JSON.stringify(found.record,null,2));}

function entryManagerDefaultCutoff_(record){
  const raw=String(record.competition&&record.competition.date||'');const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(raw);if(!m)return '';
  const d=new Date(Number(m[1]),Number(m[2])-1,Number(m[3])+1,12,0,0,0);return isNaN(d.getTime())?'':d.toISOString();
}
function entryManagerEffectiveCutoff_(record){return String(record.entrySettings.autoCloseAt||'').trim()||entryManagerDefaultCutoff_(record);}
function entryManagerEffectivePublicOpen_(record){entryManagerNormaliseRecord_(record);if(record.entrySettings.publicEntriesOpen===false)return false;const raw=entryManagerEffectiveCutoff_(record);if(!raw)return true;const cutoff=new Date(raw);return isNaN(cutoff.getTime())?true:Date.now()<cutoff.getTime();}
function entryManagerGradeCount_(record,grade){const target=entryManagerClean_(grade).toLowerCase();return record.competitors.filter(c=>entryManagerClean_(c.grade).toLowerCase()===target).length;}
function entryManagerGradeSettings_(record,grade){entryManagerNormaliseRecord_(record);return record.gradeSettings[grade]||entryManagerNewGradeSettings_();}
function entryManagerGradeSummary_(record,grade){const s=entryManagerGradeSettings_(record,grade),count=entryManagerGradeCount_(record,grade),limit=s.entryLimit||null,full=Boolean(limit&&count>=limit),open=entryManagerEffectivePublicOpen_(record)&&s.publicOpen!==false&&!s.submitted&&!full;return{name:grade,count,entryLimit:limit,remaining:limit?Math.max(0,limit-count):null,full,submitted:s.submitted===true,submittedAt:s.submittedAt||'',publicOpen:s.publicOpen!==false,selectable:open};}
function entryManagerAllSubmitted_(record){return record.grades.length>0&&record.grades.every(g=>entryManagerGradeSettings_(record,g).submitted===true);}

function entryManagerPublicSetup_(token){const record=entryManagerReadByManagerToken_(token).record;const summaries={};record.grades.forEach(g=>summaries[g]=entryManagerGradeSummary_(record,g));return{ok:true,bookingReference:record.bookingReference,accessToken:record.managerToken,competition:record.competition,grades:record.grades,gradeSettings:summaries,competitionSetup:record.competitionSetup,competitorEntryUrl:entryManagerCompetitorUrl_(record.publicEntryToken),entrySettings:{publicEntriesOpen:record.entrySettings.publicEntriesOpen!==false,autoCloseAt:String(record.entrySettings.autoCloseAt||''),effectiveCutoffAt:entryManagerEffectiveCutoff_(record),effectivePublicEntriesOpen:entryManagerEffectivePublicOpen_(record)},competitors:record.competitors.map(entry=>({id:entry.id,grade:entry.grade,name:entry.name,town:entry.town||'',phone:entry.phone||'',email:entry.email||'',source:entry.source||'manual',checkedIn:entry.checkedIn===true,createdAt:entry.createdAt||'',updatedAt:entry.updatedAt||''}))};}
function entryManagerCompetitorSetup_(token){const record=entryManagerReadByPublicToken_(token).record,gradeOptions=record.grades.map(g=>entryManagerGradeSummary_(record,g));return{ok:true,competition:record.competition,entriesOpen:entryManagerEffectivePublicOpen_(record),autoCloseAt:String(record.entrySettings.autoCloseAt||''),effectiveCutoffAt:entryManagerEffectiveCutoff_(record),grades:gradeOptions,privacyContact:ENTRY_MANAGER_SETTINGS.receiverEmail};}

function entryManagerSaveCompetitorEntry_(payload){
  if(!payload||payload.type!=='speed_shear_competitor_entry')throw new Error('Unsupported competitor entry.');
  const token=String(payload.entryToken||'').trim(),grade=entryManagerClean_(payload.grade),name=entryManagerClean_(payload.name),town=entryManagerClean_(payload.town),phone=entryManagerClean_(payload.phone),email=entryManagerClean_(payload.email).toLowerCase();
  if(!name)throw new Error('Competitor name is required.');if(!phone&&!email)throw new Error('Please provide a phone number or email address.');if(payload.privacyAccepted!==true)throw new Error('Privacy acknowledgement is required.');
  const lock=LockService.getScriptLock();lock.waitLock(30000);
  try{
    const found=entryManagerReadByPublicToken_(token),record=found.record;if(!entryManagerEffectivePublicOpen_(record))throw new Error('Public entries are closed for this competition.');if(!grade||record.grades.indexOf(grade)<0)throw new Error('Please choose a valid grade or event.');
    const summary=entryManagerGradeSummary_(record,grade);if(summary.submitted)throw new Error(grade+' entries have already been submitted and are closed.');if(!summary.publicOpen)throw new Error(grade+' public entries are closed.');if(summary.full)throw new Error(grade+' is full. The entry limit has been reached.');
    const duplicate=record.competitors.find(item=>String(item.grade||'').toLowerCase()===grade.toLowerCase()&&entryManagerClean_(item.name).toLowerCase()===name.toLowerCase()&&entryManagerClean_(item.town).toLowerCase()===town.toLowerCase());if(duplicate)return{ok:true,duplicate:true,competitionName:record.competition&&record.competition.name||'',grade,competitorName:name};
    record.competitors.push({id:Utilities.getUuid(),grade,name,town,phone,email,source:'public-entry',checkedIn:false,createdAt:new Date().toISOString()});entryManagerSaveRecord_(found);
    return{ok:true,duplicate:false,competitionName:record.competition&&record.competition.name||'',grade,competitorName:name,gradeStatus:entryManagerGradeSummary_(record,grade)};
  }finally{lock.releaseLock();}
}

function entryManagerSaveEntrySettings_(payload){if(!payload||payload.type!=='speed_shear_manager_entry_settings')throw new Error('Unsupported entry settings update.');const lock=LockService.getScriptLock();lock.waitLock(30000);try{const found=entryManagerReadByManagerToken_(payload.accessToken||''),settings=payload.entrySettings||{};let autoCloseAt=entryManagerClean_(settings.autoCloseAt);if(autoCloseAt){const parsed=new Date(autoCloseAt);if(isNaN(parsed.getTime()))throw new Error('Automatic closing date/time is invalid.');autoCloseAt=parsed.toISOString();}found.record.entrySettings={publicEntriesOpen:settings.publicEntriesOpen!==false,autoCloseAt,updatedAt:new Date().toISOString()};entryManagerSaveRecord_(found);return{ok:true,entrySettings:found.record.entrySettings,effectiveCutoffAt:entryManagerEffectiveCutoff_(found.record),effectivePublicEntriesOpen:entryManagerEffectivePublicOpen_(found.record)};}finally{lock.releaseLock();}}
function entryManagerSaveGradeSettings_(payload){if(!payload||payload.type!=='speed_shear_manager_grade_settings')throw new Error('Unsupported grade settings update.');const grade=entryManagerClean_(payload.grade),settings=payload.gradeSettings||{},lock=LockService.getScriptLock();lock.waitLock(30000);try{const found=entryManagerReadByManagerToken_(payload.accessToken||''),record=found.record;if(record.grades.indexOf(grade)<0)throw new Error('Grade or event was not found.');const current=entryManagerGradeSettings_(record,grade);let limit=settings.entryLimit==null||settings.entryLimit===''?null:Number(settings.entryLimit);if(limit!==null&&(!Number.isInteger(limit)||limit<1))throw new Error('Entry limit must be a whole number greater than zero.');record.gradeSettings[grade]={...current,publicOpen:settings.publicOpen!==false,entryLimit:limit};entryManagerSaveRecord_(found);return{ok:true,grade:entryManagerGradeSummary_(record,grade)};}finally{lock.releaseLock();}}
function entryManagerAddGrade_(payload){if(!payload||payload.type!=='speed_shear_manager_grade_add')throw new Error('Unsupported grade addition.');const name=entryManagerClean_(payload.grade);if(!name)throw new Error('Grade or event name is required.');const lock=LockService.getScriptLock();lock.waitLock(30000);try{const found=entryManagerReadByManagerToken_(payload.accessToken||'');if(!found.record.grades.some(g=>entryManagerClean_(g).toLowerCase()===name.toLowerCase())){found.record.grades.push(name);found.record.gradeSettings[name]=entryManagerNewGradeSettings_();}entryManagerSaveRecord_(found);return{ok:true,grades:found.record.grades};}finally{lock.releaseLock();}}
function entryManagerRemoveGrade_(payload){if(!payload||payload.type!=='speed_shear_manager_grade_remove')throw new Error('Unsupported grade removal.');const name=entryManagerClean_(payload.grade),lock=LockService.getScriptLock();lock.waitLock(30000);try{const found=entryManagerReadByManagerToken_(payload.accessToken||'');if(found.record.competitors.some(c=>entryManagerClean_(c.grade).toLowerCase()===name.toLowerCase()))throw new Error('Remove competitors from this grade before removing the grade.');found.record.grades=found.record.grades.filter(g=>entryManagerClean_(g).toLowerCase()!==name.toLowerCase());delete found.record.gradeSettings[name];entryManagerSaveRecord_(found);return{ok:true,grades:found.record.grades};}finally{lock.releaseLock();}}

function entryManagerUpsertCompetitor_(payload){if(!payload||payload.type!=='speed_shear_manager_competitor_upsert')throw new Error('Unsupported competitor save.');const incoming=payload.competitor||{},grade=entryManagerClean_(incoming.grade),name=entryManagerClean_(incoming.name),town=entryManagerClean_(incoming.town);if(!name)throw new Error('Competitor name is required.');const lock=LockService.getScriptLock();lock.waitLock(30000);try{const found=entryManagerReadByManagerToken_(payload.accessToken||''),record=found.record;if(!record.grades.some(g=>entryManagerClean_(g).toLowerCase()===grade.toLowerCase()))throw new Error('Grade or event is invalid.');const requestedId=String(incoming.id||'').trim();let item=requestedId?record.competitors.find(c=>String(c.id||'')===requestedId):null;const duplicate=record.competitors.some(c=>(!item||c.id!==item.id)&&entryManagerClean_(c.grade).toLowerCase()===grade.toLowerCase()&&entryManagerClean_(c.name).toLowerCase()===name.toLowerCase()&&entryManagerClean_(c.town).toLowerCase()===town.toLowerCase());if(duplicate)throw new Error('That competitor already exists in this grade.');if(!item){item={id:requestedId||Utilities.getUuid(),createdAt:incoming.createdAt||new Date().toISOString()};record.competitors.push(item);}item.grade=grade;item.name=name;item.town=town;item.phone=entryManagerClean_(incoming.phone);item.email=entryManagerClean_(incoming.email).toLowerCase();item.source=entryManagerClean_(incoming.source)||'manual';item.checkedIn=incoming.checkedIn===true;item.updatedAt=new Date().toISOString();entryManagerSaveRecord_(found);return{ok:true,competitor:item,gradeStatus:entryManagerGradeSummary_(record,grade)};}finally{lock.releaseLock();}}
function entryManagerSetCheckIn_(payload){if(!payload||payload.type!=='speed_shear_manager_competitor_checkin')throw new Error('Unsupported check-in update.');const competitorId=String(payload.competitorId||'').trim(),lock=LockService.getScriptLock();lock.waitLock(30000);try{const found=entryManagerReadByManagerToken_(payload.accessToken||''),item=found.record.competitors.find(c=>String(c.id||'')===competitorId);if(!item)throw new Error('Competitor was not found.');item.checkedIn=payload.checkedIn===true;item.updatedAt=new Date().toISOString();entryManagerSaveRecord_(found);return{ok:true,checkedIn:item.checkedIn};}finally{lock.releaseLock();}}
function entryManagerUpdateCompetitor_(payload){if(!payload||payload.type!=='speed_shear_manager_competitor_update')throw new Error('Unsupported competitor update.');return entryManagerUpsertCompetitor_({type:'speed_shear_manager_competitor_upsert',accessToken:payload.accessToken,competitor:{id:payload.competitorId,grade:payload.grade,name:payload.name,town:payload.town,phone:payload.phone||'',email:payload.email||'',source:payload.source||'public-entry',checkedIn:payload.checkedIn===true}});}
function entryManagerRemoveCompetitor_(payload){if(!payload||payload.type!=='speed_shear_manager_competitor_remove')throw new Error('Unsupported competitor removal.');const token=String(payload.accessToken||'').trim(),competitorId=String(payload.competitorId||'').trim(),lock=LockService.getScriptLock();lock.waitLock(30000);try{const found=entryManagerReadByManagerToken_(token),before=found.record.competitors.length;found.record.competitors=found.record.competitors.filter(c=>String(c.id||'')!==competitorId);if(found.record.competitors.length===before)throw new Error('Competitor was not found.');entryManagerSaveRecord_(found);return{ok:true};}finally{lock.releaseLock();}}

function entryManagerSaveSubmission_(payload){if(!payload||payload.type!=='speed_shear_roster_submission')throw new Error('Unsupported roster submission.');const token=String(payload.accessToken||'').trim(),lock=LockService.getScriptLock();lock.waitLock(30000);try{const found=entryManagerReadByManagerToken_(token),record=found.record;if(String(payload.bookingReference||'')!==record.bookingReference)throw new Error('Booking Reference does not match this competition.');const submittedAt=new Date().toISOString(),gradeNames=Object.keys(payload.grades||{});gradeNames.forEach(name=>{if(record.grades.indexOf(name)<0)throw new Error('Submitted grade is not part of this competition: '+name);});const submission={schemaVersion:2,type:'speed_shear_roster_submission',bookingReference:record.bookingReference,competition:record.competition,submission:{mode:payload.submission&&payload.submission.mode||'grade',submittedAt,version:record.submissions.length+1},grades:payload.grades||{}};record.submissions.push({submittedAt,mode:submission.submission.mode,grades:gradeNames});gradeNames.forEach(name=>{const s=entryManagerGradeSettings_(record,name);record.gradeSettings[name]={...s,publicOpen:false,submitted:true,submittedAt};});entryManagerSaveRecord_(found);const filename=entryManagerSubmissionFilename_(submission),attachment=Utilities.newBlob(JSON.stringify(submission,null,2),'application/json',filename);entryManagerFolder_().createFile(attachment.copyBlob());MailApp.sendEmail({to:ENTRY_MANAGER_SETTINGS.receiverEmail,subject:entryManagerSubmissionSubject_(submission),body:'Speed Shear entries submitted for '+record.competition.name+'. Booking Reference: '+record.bookingReference+'. The timing-system roster JSON is attached.',name:ENTRY_MANAGER_SETTINGS.senderName,attachments:[attachment]});return{ok:true,bookingReference:record.bookingReference,submittedAt,filename,allSubmitted:entryManagerAllSubmitted_(record),gradeSettings:record.gradeSettings};}finally{lock.releaseLock();}}
function entryManagerSubmissionFilename_(submission){const names=Object.keys(submission.grades||{}),gradePart=submission.submission.mode==='all'?'All_Entries':(names[0]||'Entries').replace(/[^A-Za-z0-9_-]+/g,'_'),competition=String(submission.competition&&submission.competition.name||'Competition').replace(/[^A-Za-z0-9_-]+/g,'_');return competition+'_'+submission.bookingReference+'_'+gradePart+'.json';}
function entryManagerSubmissionSubject_(submission){const names=Object.keys(submission.grades||{}),label=submission.submission.mode==='all'?'All Entries':((names[0]||'Entries')+' Entries');return label+' — '+submission.bookingReference+' — '+String(submission.competition&&submission.competition.name||'Speed Shear');}

function entryManagerResultKey_(token,requestId){return 'em_'+String(token||'').slice(0,16)+'_'+String(requestId||'').replace(/[^A-Za-z0-9_-]/g,'').slice(0,80);}
function entryManagerStorePublicSubmissionResult_(token,requestId,result){if(!token||!requestId)return;CacheService.getScriptCache().put(entryManagerResultKey_(token,requestId),JSON.stringify(result),600);}
function entryManagerPublicSubmissionResult_(token,requestId){entryManagerReadByPublicToken_(token);if(!requestId)throw new Error('Submission request ID is missing.');const raw=CacheService.getScriptCache().get(entryManagerResultKey_(token,requestId));return raw?JSON.parse(raw):{ok:false,pending:true,error:'Submission result is not ready yet.'};}
function entryManagerClean_(value){return String(value||'').trim().replace(/\s+/g,' ');}
function entryManagerJsonResponse_(obj){return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON);}
